
groups:
  - name: application_startup
    rules:
      - alert: ApplicationStarted
        expr: up{application="api-tickets"} == 1
        for: 0s
        labels:
          severity: info
        annotations:
          summary: "Aplicação Iniciada"
          description: "A aplicação Spring Boot (job {{ $labels.job }}, instance {{ $labels.instance }}) foi iniciada."