global:
  resolve_timeout: 5m

route:
  receiver: 'email-on-start'
  group_by: ['alertname', 'job']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
  - name: 'email-on-start'
    email_configs:
      # ============================================================
      # CONFIGURACAO REAL - SUBSTITUA PELOS SEUS DADOS
      # ============================================================
      - to: 'giovannidecarvalhomendes@gmail.com'          # Email que RECEBE o alerta
        from: 'alertmanager.senha@gmail.com' # Email que ENVIA o alerta
        smarthost: 'smtp.gmail.com:587'     # Servidor SMTP do Gmail
        auth_username: 'alertmanager.senha@gmail.com'  # Mesmo do 'from'
        auth_password: 'xxxx xxxx xxxx xxxx'           # Senha de app do Gmail (NAO a senha normal)
        headers:
          Subject: '[ALERT Tickets API] - {{ .GroupLabels.alertname }}'
        tls_config:
          insecure_skip_verify: false
