global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "api-tickets-jobs"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8080"]
        labels:
          application: "api-tickets"

rule_files:
  - 'rules/alerts.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'